server:
  port: 8080

spring:
  application:
    name: RateLimiter

  jmx:
    enabled: false   # ✅ CORRECT POSITION

  redis:
    host: localhost
    port: 6379
    timeout: 2000

management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

rate-limiter:
  capacity: 10
  refill-rate: 5
  api-server-url: https://localhost:8080
  timeout: 5000